2021-11-22 03:03:53,584 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 23, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/email/reset_password.html", line 1, in top-level template code
    {% extends "index.html" %}
  File "/home/danya/microblog/app/templates/index.html", line 41, in top-level template code
    {% block content %}
  File "/home/danya/microblog/app/templates/email/reset_password.html", line 9, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-11-22 03:07:51,667 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:07:52,577 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 23, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/email/reset_password.html", line 1, in top-level template code
    {% extends "index.html" %}
  File "/home/danya/microblog/app/templates/index.html", line 41, in top-level template code
    {% block content %}
  File "/home/danya/microblog/app/templates/email/reset_password.html", line 9, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-11-22 03:10:06,965 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:10:07,282 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 15, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
TypeError: send_email() got an unexpected keyword argument 'recipients'
2021-11-22 03:10:34,590 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 03:10:37,769 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 15, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "/home/danya/microblog/app/email.py", line 7, in send_email
    msg = Message(subject, sender = sender, recipient = recipient)
TypeError: __init__() got an unexpected keyword argument 'recipient'
2021-11-22 03:11:26,454 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
