2021-11-22 00:08:33,858 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 01:05:13,721 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 01:18:14,355 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 01:20:13,527 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 01:57:07,591 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:03:55,630 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:06:23,305 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:07:36,768 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:08:39,136 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:27:41,722 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:27:43,279 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:29:17,800 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:32:18,302 ERROR: Exception on /reset_password_request [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 102, in reset_password_request
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2021-11-22 02:34:11,731 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:44:30,249 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:45:15,629 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:46:25,454 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/danya/microblog/app/models.py", line 47, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in},
AttributeError: 'str' object has no attribute 'decode'
2021-11-22 02:47:27,515 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:47:36,059 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:48:03,455 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:48:19,233 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/danya/microblog/app/models.py", line 47, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-11-22 02:50:34,665 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:52:38,455 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:52:41,164 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:54:38,422 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:55:56,204 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:56:08,488 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/danya/microblog/app/models.py", line 47, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-11-22 02:58:46,072 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:58:47,667 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:58:49,817 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/danya/microblog/app/models.py", line 47, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'jwt'
2021-11-22 02:59:45,254 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
2021-11-22 02:59:54,893 ERROR: Exception on /reset_password_request [POST] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/danya/microblog/app/routes.py", line 106, in reset_password_request
    send_password_reset_email(user)
  File "/home/danya/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/danya/microblog/app/models.py", line 47, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-11-22 03:01:08,699 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:55]
