2021-11-23 17:35:23,666 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:36:56,879 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:37:00,910 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:40:04,980 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:41:05,592 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:43:14,356 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:44:51,833 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:45:22,110 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:47:22,668 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:47:23,350 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:57]
2021-11-23 17:48:05,123 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:60]
2021-11-23 17:48:54,763 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:60]
2021-11-23 17:51:37,315 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:51:51,406 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:52:15,654 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:54:28,759 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:54:37,692 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:56:19,173 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:57:39,606 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 17:58:14,098 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 18:00:39,617 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:61]
2021-11-23 18:02:19,047 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-23 18:03:22,062 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-23 18:04:51,315 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-23 18:04:52,084 ERROR: Exception on /follow/ [GET] [in /home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2041, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "/home/danya/microblog/app/errors.py", line 8, in not_found_error
    return render_template('error404.html', title='404 Error'), 404
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/danya/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/danya/microblog/app/templates/error404.html", line 4, in template
    <h1>{{ _(Page Not Found) }}</h1>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Not'
2021-11-23 19:37:19,990 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
2021-11-23 19:47:12,928 INFO: Microblog startup [in /home/danya/microblog/app/__init__.py:62]
